import type { Metadata } from "next";
import {
  LandingNav,
  LandingFooter,
  Section,
  Eyebrow,
  SectionHeading,
  Lead,
} from "@/components/landing/sections";
import { SectionTrack } from "@/components/systemix/LandingEvents";
import { AuditRequestForm } from "@/components/landing/AuditRequestForm";

export const metadata: Metadata = {
  title: "Readiness Audit — is your design system AI-ready? · Systemix",
  description:
    "Point Systemix at your repo or site and get back a scored AI-native readiness report: design-system health, the drift + slop map, an ODI opportunity ranking, and the exact setup to make your agent follow a system. One-time, read-only.",
};

// Mirrors what /readiness-audit produces (T5) so the page promises exactly what ships.
const REPORT = [
  {
    title: "Overall readiness score",
    body: "A single 0–100 number for how ready your repo is for agent-driven work — with design-system health and drift-control sub-scores.",
  },
  {
    title: "The drift + slop map",
    body: "Where colours, spacing and type drift from any real system, and the duplicate or mixed-library components your agents keep reinventing.",
  },
  {
    title: "ODI opportunity ranking",
    body: "Six readiness dimensions scored by importance vs satisfaction — most underserved first, so you know what to fix and in what order.",
  },
  {
    title: "The recommended setup",
    body: "Scaffold fresh, adopt what you have, or consolidate — the exact systemix init answers that turn the findings into a system your agent follows.",
  },
];

export default function AuditPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <LandingNav />
      <main>
        <SectionTrack name="audit-hero">
          <section className="border-b border-border/40 py-24 sm:py-28">
            <div className="mx-auto max-w-5xl px-6 text-center">
              <Eyebrow>Readiness Audit · $149–249 · one-time</Eyebrow>
              <h1 className="mx-auto max-w-3xl text-[2.5rem] font-black leading-[1.1] tracking-tight sm:text-[3rem]">
                Is your design system AI-ready?
              </h1>
              <p className="mx-auto mt-5 max-w-xl text-[16px] leading-relaxed text-muted-foreground">
                Point us at your repo or site. You get back a scored readiness report — drift, slop,
                the opportunity ranking, and the exact setup to make your agent follow a system
                instead of guessing.
              </p>
            </div>
          </section>
        </SectionTrack>

        <Section>
          <div className="max-w-3xl">
            <Eyebrow>What you get</Eyebrow>
            <SectionHeading>A scored report you can act on — not a vibe check.</SectionHeading>
            <Lead>
              Generated by the same <code className="font-mono text-[13px]">/readiness-audit</code>{" "}
              that runs in Claude Code: design-system health, drift, and an AI-native readiness
              rubric — delivered as a report and a shareable artifact.
            </Lead>
          </div>
          <div className="mt-14 grid gap-4 sm:grid-cols-2 sm:gap-5">
            {REPORT.map((r) => (
              <div key={r.title} className="rounded-xl border border-border/40 bg-card p-6">
                <p className="mb-2 text-[15px] font-bold text-foreground">{r.title}</p>
                <p className="text-[13px] leading-relaxed text-muted-foreground">{r.body}</p>
              </div>
            ))}
          </div>
        </Section>

        <SectionTrack name="audit-form">
          <Section>
            <div className="grid gap-10 sm:grid-cols-2 sm:items-start sm:gap-16">
              <div>
                <Eyebrow>Request it</Eyebrow>
                <SectionHeading>Send your repo. Get your report.</SectionHeading>
                <Lead>
                  One-time, no setup on your side. Read-only — Systemix never writes to your code;
                  the report and the seed of the fix come back to you.
                </Lead>
                <ul className="mt-6 flex flex-col gap-2 text-[14px] text-muted-foreground">
                  <li>→ Read-only — nothing written to your repo</li>
                  <li>→ Same-day reply with the report</li>
                  <li>→ Want it fixed for you? It rolls into the sprint.</li>
                </ul>
              </div>
              <AuditRequestForm />
            </div>
          </Section>
        </SectionTrack>
      </main>
      <LandingFooter />
    </div>
  );
}
