// AGENT-WRITTEN — tokens.ts
// Derived at import time from .systemix/tokens.bridge.json (generated by
// scripts/token-converter.ts from src/app/globals.css — run `npm run tokens`
// after editing globals.css). No literal values live here, so this file
// cannot drift from the token source of truth.

import bridgeJson from "../../../.systemix/tokens.bridge.json";

export type SyncStatus = "synced" | "drift" | "stale" | "new";
export type TokenCollection = "color" | "status" | "radius" | "spacing" | "typography";

export type Token = {
  name: string;          // CSS custom property (--background)
  value: string;         // Light mode value (hex for colors)
  darkValue?: string;    // Dark mode hex value (if applicable)
  figmaVariable: string; // Figma variable path (color/background)
  figmaCollection: string;
  syncStatus: SyncStatus;
  collection: TokenCollection;
  description?: string;
};

export type TokenRegistry = {
  tokens: Token[];
  lastSynced: string | null;
  figmaFileKey: string;
  connectionStatus: "connected" | "disconnected";
};

// ── Bridge file shape (DTCG + figma sidecar) ────────────────────────────────
export type BridgeEntry = {
  $type: string;
  $value: string;
  figma: {
    hex?: string;
    variableName: string;
    collection: string;
    cssVar: string;
    syncStatus: string;
    dark?: { $value: string; hex?: string };
  };
};

export type BridgeGroups = Record<string, Record<string, BridgeEntry>>;

// Strip the $schema/_meta headers; everything else is a token group.
export const bridgeGroups: BridgeGroups = Object.fromEntries(
  Object.entries(bridgeJson as unknown as Record<string, unknown>).filter(
    ([key]) => !key.startsWith("$") && !key.startsWith("_")
  )
) as BridgeGroups;

const GROUP_TO_COLLECTION: Record<string, TokenCollection> = {
  color: "color",
  sidebar: "color",
  status: "status",
  radius: "radius",
  spacing: "spacing",
  "font-size": "typography",
  font: "typography",
};

export const tokenRegistry: TokenRegistry = {
  lastSynced: null,
  figmaFileKey: "h1m7dfFILe1wGSfxwQ6U02",
  connectionStatus: "disconnected",
  tokens: Object.entries(bridgeGroups).flatMap(([group, entries]) =>
    Object.values(entries).map((t): Token => ({
      name: t.figma.cssVar,
      value: t.figma.hex ?? t.$value,
      ...(t.figma.dark?.hex ? { darkValue: t.figma.dark.hex } : {}),
      figmaVariable: t.figma.variableName,
      figmaCollection: t.figma.collection,
      syncStatus: "new",
      collection: GROUP_TO_COLLECTION[group] ?? "color",
    }))
  ),
};
