/**
 * variables.ts — design token data for the workspace
 *
 * Derived at import time from .systemix/tokens.bridge.json (generated by
 * scripts/token-converter.ts from src/app/globals.css — run `npm run tokens`
 * after editing globals.css). codeValue is the raw globals.css value; no
 * literal values live here, so this file cannot drift from the token source.
 *
 * figmaValue: null means "not yet fetched" (pending Figma pull), so every
 * derived token starts at drift: 'pending'. The bridge carries the converter's
 * "core-only" scope: semantic colors, sidebar, and the typography scale.
 *
 * drift: 'match' | 'drifted' | 'custom' | 'missing' | 'pending'
 */

import { bridgeGroups, type BridgeEntry } from "./tokens";

export type DriftStatus = "match" | "drifted" | "custom" | "missing" | "pending";
export type TokenType = "color" | "dimension" | "string" | "duration" | "shadow";
export type TokenGroup =
  | "semantic"
  | "sidebar"
  | "status"
  | "agent"
  | "typography"
  | "spacing"
  | "radius"
  | "shadow"
  | "animation";

export type DesignToken = {
  name: string; // CSS var name without --
  group: TokenGroup;
  type: TokenType;
  codeValue: string; // value in globals.css
  figmaValue: string | null; // null = pending, undefined = not in Figma
  figmaName?: string; // Figma variable name if different
  drift: DriftStatus;
  note?: string;
};

const BRIDGE_GROUP_TO_TOKEN_GROUP: Record<string, TokenGroup> = {
  color: "semantic",
  sidebar: "sidebar",
  status: "status",
  radius: "radius",
  spacing: "spacing",
  "font-size": "typography",
  font: "typography",
};

const TYPE_MAP: Record<string, TokenType> = {
  color: "color",
  dimension: "dimension",
  fontFamily: "string",
};

function toDesignToken(group: TokenGroup, entry: BridgeEntry): DesignToken {
  return {
    name: entry.figma.cssVar.replace(/^--/, ""),
    group,
    type: TYPE_MAP[entry.$type] ?? "string",
    codeValue: entry.$value,
    figmaValue: null,
    figmaName: entry.figma.variableName,
    drift: "pending",
  };
}

// ── All tokens ────────────────────────────────────────────────────────────────
export const ALL_TOKENS: DesignToken[] = Object.entries(bridgeGroups).flatMap(
  ([bridgeGroup, entries]) =>
    Object.values(entries).map((entry) =>
      toDesignToken(BRIDGE_GROUP_TO_TOKEN_GROUP[bridgeGroup] ?? "semantic", entry)
    )
);

const GROUP_META: Partial<Record<TokenGroup, { label: string; description: string }>> = {
  semantic: { label: "Semantic Colors", description: "Core shadcn/ui variables — mapped to Figma" },
  sidebar: { label: "Sidebar", description: "shadcn sidebar extension variables" },
  status: { label: "Status", description: "Synced, drifted, error states — custom" },
  typography: { label: "Typography Scale", description: "Font families + size scale" },
  spacing: { label: "Spacing", description: "4px base grid scale — custom" },
  radius: { label: "Radius", description: "Border radius scale" },
};

// Only groups the bridge actually carries, in bridge order.
export const TOKEN_GROUPS: { id: TokenGroup; label: string; description: string }[] = [
  ...new Set(ALL_TOKENS.map((t) => t.group)),
].map((id) => ({ id, ...(GROUP_META[id] ?? { label: id, description: "" }) }));
